# github actions workflow to run unit test suite
# uses pytest package

name: Tests

# run when:
# push or pull request is accepted to 
# master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# This runs all tests in the test/ folder
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
    - uses: actions/checkout@v4


    # Install python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: 'pyproject.toml'
      

    # Install GLPK - this is needed for pywr
    - name: Install GLPK and MPI
      run: |
        sudo apt-get update 
        sudo apt-get install -y glpk-utils libglpk-dev libopenmpi-dev openmpi-bin

    - name: Add GLPK to PATH
      run: echo "/usr/local/lib" | sudo tee -a /etc/ld.so.conf.d/glpk.conf && sudo ldconfig

    # based on https://github.com/marketplace/actions/restore-or-create-a-python-virtualenv#custom_virtualenv_dir
    # Note: virtual environment by default will be created under ~/venv
    # - uses: syphar/restore-virtualenv@v1
    #   id: cache-virtualenv

    # - uses: syphar/restore-pip-download-cache@v1
    #  if\: steps.cache-virtualenv.outputs.cache-hit != 'true'


    # install python dependencies
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    # run tests
    - name: Run tests
      run: pytest
