# github actions workflow to run unit test suite
# uses pytest package

name: tests

on:
  push:
    branches:
      - master

jobs:
  # This runs all tests in the test/ folder
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
    - uses: actions/checkout@v2


    # Install python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}


    # Install GLPK - this is needed for pywr
    - name: Install GLPK
      run: |
        sudo apt-get update && sudo apt-get install -y glpk-utils libglpk-dev

    - name: Add GLPK to PATH
      run: echo "/usr/local/lib" | sudo tee -a /etc/ld.so.conf.d/glpk.conf && sudo ldconfig

    - name: Install MPI
      run: sudo apt-get update && sudo apt-get install -y libopenmpi-dev openmpi-bin


    # install virtual environment with caching, so only updates when requirements.txt changes,
    # based on https://github.com/marketplace/actions/restore-or-create-a-python-virtualenv#custom_virtualenv_dir
    # Note: virtual environment by default will be created under ~/venv
    - uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv
      with:
        requirement_files: requirements.txt
    - uses: syphar/restore-pip-download-cache@v1
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'


    # install python dependencies
    - name: Install python dependencies
      run: pip install -r requirements.txt
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

    # run tests
    - name: Run tests
      run: pytest
